### ISSUE TITLE
Spaces not Tabs

### ISSUE THREAD

**Issue by rzsun** [s-zhang/puzzlehunt-tools#10]
[PEP 8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces) states "Spaces are the preferred indentation method".

Should we consider using spaces rather than tabs for this project?

**Comment by s-zhang** [comment]
I'm aware of the recommendation from PEP 8. Consistency is more important here so as long as all other contributors are willing to stick to using spaces as the indentation, I'm onboard as well. This can be done once we have #11 in place
