### ISSUE TITLE
Open source license for this project

### ISSUE THREAD

**Issue by s-zhang** [s-zhang/puzzlehunt-tools#8]
Which one should we use? Personally I prefer the [MIT License](https://opensource.org/licenses/MIT) due to its permissiveness. The GPLs are a bit too restrictive IMO. What do you guys think?

FYI here's a neat comparison chart
https://choosealicense.com/licenses/

**Comment by naarcini** [comment]
I would say it depends on your vision for this repo. Is it meant to be a free resource for anyone who wants it? Should we be able to keep credit for it and explicitly see improvements others make to it?

**Comment by naarcini** [comment]
Oh right, I meant to reply to this earlier. Ok, MIT License sounds good then. Let's use it!
